name: Manual NuGet Publication

on:
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Pack solution
      run: dotnet pack --configuration Release -o out --no-restore    
    - name: Push nuget packages to Nuget registry
      run: dotnet nuget push ./out/**/*.nupkg --skip-duplicate --no-symbols true -k ${{secrets.NUGET_TOKEN}} -s https://api.nuget.org/v3/index.json
    - name: Add GitHub registry as nuget source
      run: dotnet nuget add source https://nuget.pkg.github.com/kibnet/index.json --name github --username kibnet --password ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text
    - name: Push nuget packages to GitHub registry
      run: dotnet nuget push ./out/**/*.nupkg --skip-duplicate --no-symbols true -s "github"